- block:
  - name: Upgrade all packages
    dnf:
      name: "*"
      state: latest

  - name: Install required packages
    package:
      name: "{{item}}"
      state: latest
    loop:
      - libselinux-python
      - vagrant
      - sshfs
      - vagrant-sshfs
      - vagrant-hostmanager
      - docker
      - httpie



  become: yes
