
# Prezto
- name: Install prezto
  script: install_prezto.sh creates=/home/austin/.zprezto

- name: Link zpreztorc file
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zpreztorc.link"
    dest: /home/austin/.zpreztorc
    state: link

- name: Link zshrc file
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zshrc.link"
    dest: /home/austin/.zshrc
    state: link

- name: Add giddie prezto theme
  copy: src="prompt_giddie_setup" dest=/home/austin/.zprezto/modules/prompt/functions
