
- include: osx.yml
  when: ansible_os_family == "Darwin"

# TODO: Debian and Fedora

- name: Install tmuxinator
  gem: name=tmuxinator state=latest
  when: tmux_install_tmuxinator

- name: Symlink .tmux.conf
  when: ansible_os_family == "Darwin"
  file:
    src: "{{ dotfiles_home }}/roles/tmux/files/tmux.conf"
    dest: /home/austin/.tmux.conf
    state: link
